"""
HubSpot CRM client for the delivery worker.

Five public functions:
  ensure_custom_properties  — create AI property group + fields at worker startup
  find_or_create_contact    — search by phone, create if not found; returns (id, log)
  get_contact_log           — fetch ai_comm_log for an existing contact by id
  update_contact            — PATCH contact with AI insight properties
  create_note               — POST a Note on the contact timeline; returns note id
  find_or_create_ticket     — POST a Ticket for complaint/negative events; returns ticket id

WHY httpx instead of the hubspot-api-client SDK:
The project already uses httpx for outbound HTTP. Adding the official SDK would
introduce a heavy dependency (many generated classes) for only the API calls we need.
Using httpx directly keeps the dependency surface small and reuses the same connection
pooling and retry logic already in the delivery worker.

WHY we need these scopes:
  crm.objects.contacts.read   — search for existing contacts by phone
  crm.objects.contacts.write  — create new contacts, update properties
  crm.schemas.contacts.write  — create the custom AI property group and fields
  crm.objects.tickets.write   — create Tickets for complaints / negative sentiment

The token is never logged (security rule). Authorization header is built by the
private _auth_headers() helper so the token never appears in call sites.
"""

from __future__ import annotations

import httpx
import structlog

log = structlog.get_logger(__name__)

# HubSpot property group that holds all AI-generated fields.
_GROUP_NAME = "ai_insights"

# Intent closed-set values — must match VALID_INTENTS in intelligence_layer/enrichment.py.
_INTENT_OPTIONS = [
    {"label": "Support Request", "value": "support_request", "displayOrder": 0, "hidden": False},
    {"label": "Sales Inquiry",   "value": "sales_inquiry",   "displayOrder": 1, "hidden": False},
    {"label": "Complaint",       "value": "complaint",       "displayOrder": 2, "hidden": False},
    {"label": "Appointment",     "value": "appointment",     "displayOrder": 3, "hidden": False},
    {"label": "Billing Question","value": "billing_question","displayOrder": 4, "hidden": False},
    {"label": "Cancellation",    "value": "cancellation",    "displayOrder": 5, "hidden": False},
    {"label": "General Query",   "value": "general_query",   "displayOrder": 6, "hidden": False},
]

_SENTIMENT_OPTIONS = [
    {"label": "Positive", "value": "positive", "displayOrder": 0, "hidden": False},
    {"label": "Neutral",  "value": "neutral",  "displayOrder": 1, "hidden": False},
    {"label": "Negative", "value": "negative", "displayOrder": 2, "hidden": False},
]

# Custom contact properties we create once and write on every delivery.
# Enum properties enable native HubSpot reports, list filters, and workflow triggers.
# 'text' fieldType = single-line. 'textarea' = multi-line for long values.
_PROPERTY_DEFINITIONS = [
    {
        "name": "ai_last_intent",
        "label": "AI Last Intent",
        "description": "Primary intent of the most recent AI-analysed communication.",
        "type": "enumeration",
        "fieldType": "select",
        "options": _INTENT_OPTIONS,
        "displayOrder": 1,
    },
    {
        "name": "ai_last_sentiment",
        "label": "AI Last Sentiment",
        "description": "Overall sentiment of the most recent AI-analysed communication.",
        "type": "enumeration",
        "fieldType": "select",
        "options": _SENTIMENT_OPTIONS,
        "displayOrder": 2,
    },
    {
        "name": "ai_last_summary",
        "label": "AI Last Summary",
        "description": "1–3 sentence AI summary of the most recent communication.",
        "type": "string",
        "fieldType": "textarea",
        "displayOrder": 3,
    },
    {
        "name": "ai_last_action_items",
        "label": "AI Action Items",
        "description": "Follow-up tasks generated by AI for the most recent communication.",
        "type": "string",
        "fieldType": "textarea",
        "displayOrder": 4,
    },
    {
        "name": "ai_last_channel",
        "label": "AI Last Channel",
        "description": "Channel of the most recent communication (sms, whatsapp, voice).",
        "type": "string",
        "fieldType": "text",
        "displayOrder": 5,
    },
    {
        "name": "ai_comm_log",
        "label": "AI Communication Log",
        "description": "Prepend-only history of every AI-enriched communication.",
        "type": "string",
        "fieldType": "textarea",
        "displayOrder": 6,
    },
]


def _auth_headers(token: str) -> dict[str, str]:
    """Build the Authorization header. Token is intentionally never logged."""
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }


def normalize_phone(phone: str | None) -> str | None:
    """
    Strip the 'whatsapp:' prefix Twilio adds to WhatsApp numbers.

    WhatsApp from_number arrives as 'whatsapp:+15551234567'. HubSpot expects
    a plain E.164 string. Contacts created with the prefix would never match
    a search for the plain number, causing duplicate contacts on every retry.
    """
    if phone and phone.startswith("whatsapp:"):
        return phone[len("whatsapp:"):]
    return phone


async def ensure_custom_properties(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
) -> None:
    """
    Create the AI Insights property group and all custom properties.

    Safe to call on every worker startup — 409 Conflict means the property
    already exists. For enum properties: if the property exists but has the wrong
    type (e.g. created as free-text before this upgrade), we log a loud warning
    with instructions instead of auto-deleting. The one-time delete must be done
    manually in HubSpot Settings → Properties.

    We log warnings for any other unexpected error but do not raise: a property
    creation failure should not prevent the worker from starting up.
    """
    headers = _auth_headers(token)

    # Create the property group that organises all AI fields in the HubSpot UI.
    resp = await client.post(
        f"{base_url}/crm/v3/properties/contacts/groups",
        headers=headers,
        json={"name": _GROUP_NAME, "label": "AI Insights", "displayOrder": -1},
        timeout=10.0,
    )
    if resp.status_code not in (200, 201, 409):
        log.warning(
            "hubspot.property_group_creation_failed",
            status=resp.status_code,
            body=resp.text[:200],
        )

    # Create each custom property inside the group.
    for prop in _PROPERTY_DEFINITIONS:
        # Check if the property already exists with a conflicting type.
        check_resp = await client.get(
            f"{base_url}/crm/v3/properties/contacts/{prop['name']}",
            headers=headers,
            timeout=10.0,
        )
        if check_resp.status_code == 200:
            existing_type = check_resp.json().get("type", "")
            if existing_type != prop["type"]:
                log.warning(
                    "hubspot.property_type_mismatch_manual_action_required",
                    property_name=prop["name"],
                    existing_type=existing_type,
                    required_type=prop["type"],
                    action=(
                        f"Go to HubSpot → Settings → Properties → Contacts, "
                        f"find '{prop['label']}', delete it, then restart the worker. "
                        f"This one-time step converts it to a filterable dropdown."
                    ),
                )
            continue  # property exists (right or wrong type) — skip creation

        resp = await client.post(
            f"{base_url}/crm/v3/properties/contacts",
            headers=headers,
            json={**prop, "groupName": _GROUP_NAME},
            timeout=10.0,
        )
        if resp.status_code not in (200, 201, 409):
            log.warning(
                "hubspot.property_creation_failed",
                property_name=prop["name"],
                status=resp.status_code,
                body=resp.text[:200],
            )

    log.info("hubspot.custom_properties_ensured")


async def find_or_create_contact(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    phone: str,
) -> tuple[str, str]:
    """
    Find a HubSpot contact by phone number, or create one if not found.

    Returns (contact_id, existing_ai_comm_log).
    The existing log is used by the caller to prepend new history entries.

    WHY search before create:
    HubSpot does not enforce phone uniqueness by default. Creating without
    searching would make a new contact on every delivery attempt for the same
    caller — the classic "3,000 duplicate contacts" CRM mess. Searching first
    and reusing existing contacts keeps the CRM clean.

    WHY we request ai_comm_log in the search:
    Fetching the current log during search avoids a separate GET call later.
    The caller prepends the new entry to this existing value.

    NOTE: 'id' is intentionally NOT in the properties list — it is not a
    HubSpot property name; the contact id is always returned at the top level.
    Some HubSpot versions reject unknown property names in the list.

    Raises httpx.HTTPStatusError on non-2xx responses so the delivery worker
    can apply its standard ack/nack/dead-letter logic based on the status code.
    """
    headers = _auth_headers(token)
    clean_phone = normalize_phone(phone)

    search_resp = await client.post(
        f"{base_url}/crm/v3/objects/contacts/search",
        headers=headers,
        json={
            "filterGroups": [
                {
                    "filters": [
                        {
                            "propertyName": "phone",
                            "operator": "EQ",
                            "value": clean_phone,
                        }
                    ]
                }
            ],
            "properties": ["phone", "ai_comm_log"],
            "limit": 1,
        },
        timeout=10.0,
    )
    search_resp.raise_for_status()

    results = search_resp.json().get("results", [])
    if results:
        contact = results[0]
        existing_log = (contact.get("properties") or {}).get("ai_comm_log") or ""
        log.debug("hubspot.contact_found", contact_id=contact["id"])
        return contact["id"], existing_log

    # Contact not found — create a new one.
    create_resp = await client.post(
        f"{base_url}/crm/v3/objects/contacts",
        headers=headers,
        json={"properties": {"phone": clean_phone}},
        timeout=10.0,
    )
    create_resp.raise_for_status()

    contact_id = create_resp.json()["id"]
    log.info("hubspot.contact_created", contact_id=contact_id)
    return contact_id, ""


async def get_contact_log(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    contact_id: str,
) -> str:
    """
    Fetch the current ai_comm_log for an existing contact by ID.

    WHY this exists:
    On retries, hubspot_contact_id is already persisted so we skip
    find_or_create_contact entirely — but we must still read the current log
    before prepending the new entry. Without this, the PATCH would overwrite
    the entire history with only the current event, destroying all prior entries.

    Returns the current log value, or "" if the property is not yet set.
    Raises httpx.HTTPStatusError on non-2xx so the delivery worker maps errors
    to nack/dead-letter via its standard _handle_http_error helper.
    """
    headers = _auth_headers(token)
    resp = await client.get(
        f"{base_url}/crm/v3/objects/contacts/{contact_id}",
        headers=headers,
        params={"properties": "ai_comm_log"},
        timeout=10.0,
    )
    resp.raise_for_status()
    properties = resp.json().get("properties") or {}
    return properties.get("ai_comm_log") or ""


async def update_contact(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    contact_id: str,
    properties: dict[str, str],
) -> httpx.Response:
    """
    PATCH a contact with the given properties dict.

    Returns the raw httpx.Response. The caller (process_message) is responsible
    for calling raise_for_status() and mapping the status code to ack/nack/dead-letter.
    This keeps all retry-policy decisions in one place (main.py).
    """
    headers = _auth_headers(token)
    return await client.patch(
        f"{base_url}/crm/v3/objects/contacts/{contact_id}",
        headers=headers,
        json={"properties": properties},
        timeout=10.0,
    )


def _post_note_payload(
    body: str, timestamp_ms: int, target_id: str, association_type_id: int
) -> dict:
    """Build the JSON payload for a Note POST regardless of what it's linked to."""
    return {
        "properties": {
            "hs_note_body": body,
            "hs_timestamp": str(timestamp_ms),
        },
        "associations": [
            {
                "to": {"id": target_id},
                "types": [
                    {
                        "associationCategory": "HUBSPOT_DEFINED",
                        "associationTypeId": association_type_id,
                    }
                ],
            }
        ],
    }


async def create_note(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    contact_id: str,
    body: str,
    timestamp_ms: int,
) -> str:
    """
    Create a Note on the contact timeline and associate it to the contact.

    Returns the HubSpot note id (persisted to comm_events for idempotency —
    subsequent retries skip this call if the id is already set).

    WHY inline associations:
    The Notes API accepts associations in the create payload, saving a second
    API call. The association typeId 202 is HUBSPOT_DEFINED for note→contact.

    Raises httpx.HTTPStatusError on non-2xx.
    """
    headers = _auth_headers(token)
    resp = await client.post(
        f"{base_url}/crm/v3/objects/notes",
        headers=headers,
        json=_post_note_payload(body, timestamp_ms, contact_id, 202),
        timeout=10.0,
    )
    resp.raise_for_status()
    note_id = resp.json()["id"]
    log.info("hubspot.note_created", note_id=note_id, contact_id=contact_id)
    return note_id


async def add_note_to_ticket(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    ticket_id: str,
    body: str,
    timestamp_ms: int,
) -> str:
    """
    Attach a Note to an existing Ticket timeline.

    Used when a repeat complaint is received and we reuse the open ticket instead
    of creating a new one — the new message is recorded as a Note inside the ticket
    so the rep sees the full thread in one place.

    Association typeId 228 is HUBSPOT_DEFINED for note→ticket.
    Raises httpx.HTTPStatusError on non-2xx.
    """
    headers = _auth_headers(token)
    resp = await client.post(
        f"{base_url}/crm/v3/objects/notes",
        headers=headers,
        json=_post_note_payload(body, timestamp_ms, ticket_id, 228),
        timeout=10.0,
    )
    resp.raise_for_status()
    note_id = resp.json()["id"]
    log.info("hubspot.ticket_note_added", note_id=note_id, ticket_id=ticket_id)
    return note_id


async def find_or_create_ticket(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    contact_id: str,
    subject: str,
    content: str,
    pipeline: str,
    pipeline_stage: str,
    *,
    existing_ticket_id: str | None = None,
    closed_stage: str = "4",
) -> tuple[str, bool]:
    """
    Find an open ticket for this contact or create a new one.

    Returns (ticket_id, reused):
      reused=True  — an existing open ticket was found; caller should add a Note to it.
      reused=False — a new ticket was created.

    WHY open-ticket dedup:
    Per-event idempotency (hubspot_ticket_id column) prevents duplicates on retry.
    But a contact who sends multiple complaint messages over time would accumulate
    one ticket per message without this check. We look up the most recent ticket id
    from our own DB (strongly consistent), then confirm its stage via a by-id GET
    (immediately consistent) rather than using HubSpot's search index (eventually
    consistent and could return stale data for recently created tickets).

    If existing_ticket_id is provided:
    - Ticket is still open (stage != closed_stage) → return (id, True)
    - Ticket is closed or 404 (deleted) → fall through and create a new one.

    Requires crm.objects.tickets.write + crm.objects.tickets.read scopes.
    Raises httpx.HTTPStatusError on non-2xx (except 404 which is handled internally).
    """
    headers = _auth_headers(token)

    if existing_ticket_id:
        check_resp = await client.get(
            f"{base_url}/crm/v3/objects/tickets/{existing_ticket_id}",
            headers=headers,
            params={"properties": "hs_pipeline_stage"},
            timeout=10.0,
        )
        if check_resp.status_code == 404:
            log.info("hubspot.ticket_not_found_will_create", ticket_id=existing_ticket_id)
        elif check_resp.status_code >= 400:
            check_resp.raise_for_status()
        else:
            stage = (check_resp.json().get("properties") or {}).get("hs_pipeline_stage", "")
            if stage != closed_stage:
                log.info("hubspot.ticket_reused", ticket_id=existing_ticket_id, stage=stage)
                return existing_ticket_id, True
            log.info("hubspot.ticket_closed_will_create", ticket_id=existing_ticket_id, stage=stage)

    resp = await client.post(
        f"{base_url}/crm/v3/objects/tickets",
        headers=headers,
        json={
            "properties": {
                "subject": subject,
                "content": content,
                "hs_pipeline": pipeline,
                "hs_pipeline_stage": pipeline_stage,
                "hs_ticket_priority": "HIGH",
            },
            "associations": [
                {
                    "to": {"id": contact_id},
                    "types": [
                        {
                            "associationCategory": "HUBSPOT_DEFINED",
                            "associationTypeId": 16,
                        }
                    ],
                }
            ],
        },
        timeout=10.0,
    )
    resp.raise_for_status()
    ticket_id = resp.json()["id"]
    log.info("hubspot.ticket_created", ticket_id=ticket_id, contact_id=contact_id)
    return ticket_id, False


async def create_task(
    client: httpx.AsyncClient,
    token: str,
    base_url: str,
    contact_id: str,
    subject: str,
    body: str,
    due_at_ms: int,
    priority: str = "HIGH",
) -> str:
    """
    Create a HubSpot Task and associate it to a contact.

    Tasks appear in the rep's to-do queue (unlike Notes which are only on the
    contact timeline). Used when the WhatsApp bot cannot answer a customer's
    question so the rep knows they must follow up personally.

    due_at_ms: Unix timestamp in milliseconds for the task due date.
    Association typeId 204 is HUBSPOT_DEFINED for task→contact.

    Requires crm.objects.tasks.write scope on the Private App.
    Raises httpx.HTTPStatusError on non-2xx.
    """
    headers = _auth_headers(token)
    resp = await client.post(
        f"{base_url}/crm/v3/objects/tasks",
        headers=headers,
        json={
            "properties": {
                "hs_task_subject": subject,
                "hs_task_body": body,
                "hs_task_status": "NOT_STARTED",
                "hs_task_priority": priority,
                "hs_timestamp": str(due_at_ms),
                "hs_task_type": "TODO",
            },
            "associations": [
                {
                    "to": {"id": contact_id},
                    "types": [
                        {
                            "associationCategory": "HUBSPOT_DEFINED",
                            "associationTypeId": 204,
                        }
                    ],
                }
            ],
        },
        timeout=10.0,
    )
    resp.raise_for_status()
    task_id = resp.json()["id"]
    log.info("hubspot.task_created", task_id=task_id, contact_id=contact_id)
    return task_id
